package com.studenttracker.ui;
import com.studenttracker.database.DatabaseManager; import com.studenttracker.model.*; import com.studenttracker.service.*; import com.studenttracker.util.InputValidator; import java.time.*; import java.util.*;
public class ConsoleUI {private final Scanner sc=new Scanner(System.in);private final TaskService tasks;private final StudySessionService sessions;private final SchedulerService scheduler=new SchedulerService();private final ProductivityService productivity;private final BackupService backup=new BackupService();private final DatabaseManager db;public ConsoleUI(DatabaseManager db){this.db=db;tasks=new TaskService(db);sessions=new StudySessionService(db);productivity=new ProductivityService(db);} public void run(){System.out.println("\n=== SMART STUDENT TASK & PRODUCTIVITY TRACKER ===");boolean on=true;while(on){menu();try{switch(readInt("Choice: ")){case 1->addTask();case 2->showTasks(tasks.all());case 3->recommend();case 4->startStudy();case 5->dashboard();case 6->upcoming();case 7->complete();case 8->delete();case 9->backup();case 0->on=false;default->System.out.println("Invalid choice.");}}catch(Exception e){System.out.println("Error: "+e.getMessage());}}System.out.println("Goodbye!");}
 private void menu(){System.out.println("\n1 Add Task\n2 View Tasks\n3 Smart Recommendation\n4 Record Study Session\n5 Productivity Dashboard\n6 Upcoming/Overdue Tasks\n7 Complete Task\n8 Delete Task\n9 Backup Database\n0 Exit");}
 private void addTask()throws Exception{String title=read("Title: "),subject=read("Subject: "),desc=read("Description: ");Priority p=Priority.valueOf(read("Priority (LOW/MEDIUM/HIGH): ").toUpperCase());LocalDate d=InputValidator.parseDate(read("Deadline (YYYY-MM-DD): "));double h=Double.parseDouble(read("Estimated hours: "));int id=tasks.add(new Task(title,subject,desc,p,d,h));System.out.println("Task added with ID "+id);}
 private void showTasks(List<Task> list){if(list.isEmpty()){System.out.println("No tasks found.");return;}System.out.println("ID | Title | Subject | Priority | Deadline | Hours | Status");list.forEach(System.out::println);}
 private void recommend()throws Exception{var r=scheduler.recommend(tasks.pending());if(r.isEmpty())System.out.println("No pending tasks.");else{Task t=r.get();System.out.printf("\nRecommended: %s%nScore: %.1f%nDeadline: %s%nPriority: %s%nEstimated effort: %.1f hours%n",t.getTitle(),scheduler.score(t),t.getDeadline(),t.getPriority(),t.getEstimatedHours());}}
 private void startStudy()throws Exception{String subject=read("Subject: ");int min=readInt("Minutes studied: ");if(min<=0)throw new IllegalArgumentException("Minutes must be positive.");LocalDateTime end=LocalDateTime.now(),start=end.minusMinutes(min);sessions.add(new StudySession(subject,start,end,min));System.out.println("Study session recorded.");}
 private void dashboard(){int pending=productivity.count("PENDING"),progress=productivity.count("IN_PROGRESS"),done=productivity.count("COMPLETED"),total=pending+progress+done;double rate=total==0?0:done*100.0/total;System.out.printf("\nTasks total: %d | Completed: %d | Pending: %d | In progress: %d%nCompletion rate: %.1f%%%nOverdue: %d%nStudy time: %.1f hours%n",total,done,pending,progress,rate,productivity.overdue(),sessions.totalMinutes()/60.0);var map=productivity.subjectMinutes();if(!map.isEmpty()){System.out.println("Study time by subject:");map.forEach((k,v)->System.out.printf("  %-20s %.1f h%n",k,v/60.0));}}
 private void upcoming()throws Exception{var list=tasks.pending();list.stream().filter(t->t.getDeadline().isBefore(LocalDate.now().plusDays(8))).forEach(t->System.out.printf("%s | %s | %s%n",t.getDeadline(),t.getPriority(),t.getTitle()));}
 private void complete()throws Exception{tasks.complete(readInt("Task ID: "));System.out.println("Task completed.");} private void delete()throws Exception{tasks.delete(readInt("Task ID: "));System.out.println("Task deleted.");} private void backup()throws Exception{System.out.println("Backup created: "+backup.backup());} private String read(String p){System.out.print(p);return sc.nextLine().trim();}private int readInt(String p){return Integer.parseInt(read(p));}}
